source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JDSlider_Example' do
  pod 'JDSlider', :path => '../'
end

target 'JDSlider_Tests' do
  pod 'JDSlider', :path => '../'

  
end
